In [6]:
import pandas as pd
import country_parser as cp
import re, os

In [7]:
assault = pd.read_csv("./raw_data/assault_countries.csv")
un = pd.read_csv("./raw_data/unlocode.csv")

In [8]:
def lowercase(s):
    return s.lower()

k = un[un.AF.apply(lambda x: str(x)[0] == "K")].sort_values(by="AF")
k["lower"] = k.Afghanistan.apply(lowercase)
k[["lower", "AF"]]

                                     lower  AF
114                                  kenya  KE
119                             kyrgyzstan  KG
35                                cambodia  KH
115                               kiribati  KI
47                                 comoros  KM
185                  saint kitts and nevis  KN
116  democratic people's republic of korea  KP
117                      republic of korea  KR
118                                 kuwait  KW
39                          cayman islands  KY
113                             kazakhstan  KZ

In [9]:
assault["code"] = assault.Country.apply(cp.country_parser)

In [10]:
assault[assault.code == False]

,Unnamed: 0,Country,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,code
24,15,Cabo Verde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,838.8,821.5,831.7,804.4,False
30,111,Croatia,28.3,26.2,26.3,24.4,25.0,25.9,24.3,22.7,20.2,21.0,19.2,False
32,88,Czech Republic,NaN,231.0,212.0,186.6,189.1,171.7,161.0,171.2,182.9,172.2,174.6,False
36,45,Ecuador,53.3,58.9,56.3,46.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
38,31,El Salvador*,NaN,NaN,76.2,75.7,48.5,55.7,63.1,62.6,58.8,67.1,68.2,False
42,74,Georgia,NaN,8.2,8.2,6.1,3.5,4.5,3.0,2.9,NaN,NaN,NaN,False
44,112,Greece,69.5,68.9,70.4,66.9,70.4,72.3,70.9,68.7,45.2,41.3,50.4,False
45,24,Grenada,NaN,NaN,"1,839.7","1,842.9","1,266.6","1,236.4","1,320.3","1,591.6","2,112.8","1,909.3",NaN,False
46,32,Guatemala,NaN,52.1,48.1,46.6,46.8,51.0,54.3,52.0,42.4,40.4,NaN,False
47,17,Guinea,NaN,NaN,3.0,NaN,2.9,NaN,NaN,NaN,NaN,NaN,NaN,False
48,46,Guyana*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,422.4",NaN,"1,240.6",813.0,False
49,33,Honduras,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.9,25.5,21.4,False
50,54,Hong Kong Special Administrative Region of China,112.3,113.3,117.3,125.7,124.9,120.7,116.1,107.8,103.7,102.6,91.9,False
51,89,Hungary,112.8,123.7,122.2,114.3,110.8,127.0,123.7,145.1,142.1,139.9,134.3,False
52,99,Iceland,NaN,NaN,NaN,18.6,16.4,24.9,25.2,17.9,18.6,22.7,27.9,False
53,66,India,NaN,24.9,24.0,23.2,23.6,24.3,23.5,24.0,24.8,26.9,26.7,False
54,60,Indonesia,NaN,NaN,NaN,NaN,NaN,14.2,15.0,13.3,14.7,12.5,14.1,False
55,100,Ireland,294.0,299.9,300.1,325.1,353.0,372.0,353.3,336.6,325.2,296.5,272.5,False
56,75,Israel,NaN,775.6,774.0,752.6,649.7,639.3,NaN,620.0,571.0,NaN,NaN,False
57,113,Italy,NaN,88.9,96.5,100.1,106.9,109.9,109.0,107.2,112.8,114.2,108.7,False
58,25,Jamaica*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.3,NaN,205.3,177.3,False
59,55,Japan,46.2,47.0,47.5,51.1,49.5,47.2,44.2,44.2,43.4,47.1,46.7,False
60,76,Jordan,NaN,NaN,280.1,289.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
61,50,Kazakhstan,NaN,NaN,NaN,16.2,12.9,12.5,10.3,10.0,12.2,10.2,8.3,False
62,1,Kenya,NaN,NaN,35.5,35.9,32.0,29.6,35.6,34.4,34.2,33.7,30.8,False
63,114,Kosovo under UNSCR 1244,NaN,NaN,NaN,NaN,NaN,188.1,196.1,207.2,205.0,207.2,35.3,False
64,77,Kuwait,NaN,29.2,25.9,26.1,28.7,23.8,24.1,NaN,NaN,NaN,NaN,False
65,51,Kyrgyzstan,4.5,4.2,5.2,4.1,6.7,6.7,6.8,10.0,8.9,7.6,5.5,False
66,101,Latvia*,38.6,38.6,49.4,70.5,58.0,62.9,57.5,58.6,56.0,64.3,22.3,False
67,78,Lebanon,NaN,NaN,NaN,NaN,NaN,189.9,208.5,209.1,188.0,176.0,156.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,8,Sao Tome and Principe,0.7,0.7,NaN,0.0,2.4,0.6,2.9,0.0,2.2,NaN,NaN,False
102,19,Senegal,NaN,NaN,2.5,2.2,1.5,4.4,2.3,2.4,NaN,NaN,NaN,False
103,118,Serbia,NaN,NaN,16.2,16.8,17.1,16.2,14.9,14.4,13.6,13.8,13.5,False
104,20,Sierra Leone,NaN,NaN,NaN,NaN,343.8,359.2,NaN,NaN,NaN,NaN,NaN,False
105,62,Singapore,13.9,12.5,13.5,13.8,8.5,9.1,8.2,8.4,7.8,8.5,8.8,False
106,94,Slovakia,75.7,70.7,72.3,59.3,54.9,49.9,48.3,44.6,40.9,40.1,37.0,False
107,119,Slovenia,120.5,119.3,115.2,121.0,122.9,105.0,106.5,106.2,95.7,98.3,89.2,False
108,133,Solomon Islands,NaN,263.6,258.5,243.0,240.6,217.9,NaN,NaN,NaN,NaN,NaN,False
110,69,Sri Lanka,113.7,107.3,NaN,NaN,NaN,246.7,287.7,311.3,317.7,313.5,305.2,False
111,26,St. Kitts and Nevis,NaN,NaN,NaN,NaN,NaN,NaN,299.1,310.6,272.3,NaN,NaN,False
112,27,St. Vincent and the Grenadines,NaN,"1,408.4","1,151.3",967.8,974.8,942.7,"1,116.7","1,197.4","1,138.5","1,016.7",NaN,False
113,81,State of Palestine*,154.2,166.5,184.6,NaN,NaN,NaN,6.7,7.1,8.3,8.2,NaN,False
114,14,Swaziland,"1,353.5","1,332.4",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
115,104,Sweden,728.9,747.0,804.5,847.3,898.1,915.8,926.7,936.4,946.7,915.2,839.8,False
117,82,Syrian Arab Republic,31.2,36.0,33.9,29.5,3.3,2.7,NaN,NaN,NaN,NaN,NaN,False
118,52,Tajikistan,NaN,NaN,NaN,82.9,80.6,101.7,127.4,72.0,47.8,NaN,NaN,False
119,63,Thailand,NaN,NaN,43.1,39.2,40.3,28.4,27.7,24.7,NaN,NaN,NaN,False
120,121,The former Yugoslav Rep. of Macedonia,NaN,NaN,NaN,21.1,16.6,10.1,10.9,11.8,11.4,10.0,10.3,False
121,28,Trinidad and Tobago,NaN,49.8,61.8,50.4,51.9,58.6,52.1,46.4,40.1,43.3,40.4,False
122,83,Turkey,139.5,145.3,156.1,202.5,175.4,236.5,272.4,306.2,326.3,354.5,NaN,False
123,53,Turkmenistan,NaN,NaN,1.9,1.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
124,5,Uganda,72.6,92.7,122.2,147.4,93.9,66.7,52.1,67.6,NaN,NaN,NaN,False
125,95,Ukraine,11.9,11.7,14.2,13.8,12.3,10.7,11.0,8.7,NaN,NaN,NaN,False
127,105,United Kingdom (England and Wales),861.7,965.5,"1,010.6",935.5,828.8,764.2,723.7,658.8,599.7,549.7,564.3,False
128,106,United Kingdom (Northern Ireland),65.5,63.5,63.4,66.8,65.2,87.1,89.5,80.4,79.7,70.1,59.7,False
129,107,United Kingdom (Scotland),"1,229.8","1,583.0","1,538.1","1,649.9","1,538.2","1,535.5","1,477.0","1,438.7","1,385.7","1,209.0","1,188.3",False
130,39,United States of America,293.3,286.8,289.2,290.5,285.2,275.1,262.5,250.4,238.9,240.0,226.3,False
131,49,Uruguay,NaN,NaN,NaN,18.5,19.7,22.9,25.3,15.4,15.2,13.8,12.5,False
132,85,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,False
133,6,Zimbabwe,619.1,753.0,727.8,609.3,500.8,400.9,NaN,NaN,NaN,NaN,NaN,False

In [ ]:
un

In [ ]:
re.findall("algeria", "Algeria*".lower())